### ISSUE TITLE
Graph operations

### ISSUE THREAD

**Issue by fantoine** [arangodb/aqbjs#21]
Hi,
I didn't found anything about graph requests.
Are they missing from this query builder?

**Comment by fantoine** [comment]
I saw issue #12 but it's only about `GRAPH_*` functions. `INBOUND` and `OUTBOUND` keywords are still missing.

**Comment by pluma** [comment]
You're right. AQL hasn't been extended for graph operations yet. Please apologize the delay.

Starting with ArangoDB 2.8 it is recommended that you use the `aqlQuery` string template handler provided by ArangoDB and the arangojs driver to write queries unless you need the dynamic query building possible with AQB (e.g. constructing filter expressions ad hoc).

Since we're currently working on putting the finishing touches on ArangoDB 3.0 I can't give you an ETA on adding these keywords. I'll try to look into it after the release, however.

**Comment by sylvainlap** [comment]
Will you implement graph operators (INBOUND, OUTBOUND...) in aqb ?
