### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by gozes** [arangodb/aqbjs#23]
I use this aqb with  typescript and  it sort of works but it would be nice to have proper type definitions for typescript so I can take full advantage of typescript features

**Comment by pluma** [comment]
I would strongly recommend using the `aql` template string handler supported in all recent versions of ArangoDB and the arangojs driver instead.

* [ArangoDB documentation](https://docs.arangodb.com/3.1/Manual/Foxx/Modules.html#the-aql-template-string-handler)
* [arangojs documentation](https://github.com/arangodb/arangojs#aql)

In older versions of ArangoDB this template handler is also exposed as the global `aqlQuery` variable.

The AQB module is currently lagging significantly behind ArangoDB in terms of the AQL features it supports and is very resource intensive to maintain. The `aql` template string handler works without having to implement the full AQL grammar and doesn't need to be updated when new AQL features are implemented in ArangoDB.

If you wish to provide your own Typescript definitions for AQB, you're welcome to submit a PR but since AQB basically represents an entire AQL grammar that might take a while.

**Comment by Athenkosi-Mase** [comment]
There are type definitions for node [here](https://www.npmjs.com/package/@types/aqb)
