### ISSUE TITLE
Is this lib production ready? 

### ISSUE THREAD

**Issue by ashim-k-saha** [arangodb/aqbjs#27]
No one maintains this repository for a long time. That is why I have a doubt should I use this lib or not.

**Comment by mpv1989** [comment]
Hi @ashimsaha ,

We don't recommend using this lib anymore. We've implemented an [aql template handler](https://github.com/arangodb/arangojs/blob/master/docs/Drivers/JS/Reference/README.md#aql) in arangojs which should be used instead.

best
Mark

**Comment by yess-webioza** [comment]
Honestly it's a shame. This lib really helps. How to create a query using [aql template handler](https://github.com/arangodb/arangojs/blob/master/docs/Drivers/JS/Reference/README.md#aql) when u don't know (for example) which filters will be used in query? **- Simply how to assemble query??**

**Comment by Simran-B** [comment]
Can you tell a bit about your specific use case? Do you want to generate queries based on user input, e.g. a visual query builder like shown here?

![image](https://user-images.githubusercontent.com/7819991/38734075-8fb81078-3f24-11e8-9c27-b68697b0cb6e.png)

**Comment by yess-webioza** [comment]
@Simran-B Yes, that's exactly one of use cases where this ability would be useful.

**Comment by ipalfy** [comment]
While learning arangoDB I found this query builder a really nice one. Especially since I am used to c# linq.

However I did not found any similar functionality in the node.js driver. Can anyone comment on this?

BTW: It would be awesome to see the jquery-query-builder in action as shown in @Simran-B s comment.

Yes, AQL is nice and I already managed to do useful things with orientDBs SQL dialect. However, anything (x)QL isn't code. So no autocomplete, no linting, no fun ...

**Comment by pluma** [comment]
FWIW we're adding `aql.literal` (which is similar to AQB's `expr`) in ArangoDB 3.4.0 and already backported it to 3.3.9. We'll also add it to arangojs. Sadly there's no easy way to make `aql` nestable.

If you want to help us add syntax highlighting for editors and IDEs check out https://github.com/arangodb/arangodb/issues/1755

**Comment by pluma** [comment]
Just a heads up: `aql` will be nestable as of ArangoDB 3.4.0 and the next release of the arangojs driver. You can already give it a try using ArangoDB v3.4.0-rc.2.
